In [2]:
%pdb off

Automatic pdb calling has been turned OFF

In [3]:
%load_ext autoreload
%autoreload 2

# Must be set before numpy/scipy/statsmodels are imported (BLAS reads these at
# init). Multi-threaded MKL on this machine crashes the whole process outright
# (no exception, no crash dump) on any sizeable matrix op -- e.g. a single
# np.dot on a ~7.8M-row array, which statsmodels' Logit.predict() calls on
# every optimizer iteration. Forcing single-threaded BLAS fixed it completely
# (verified: the same np.dot that reliably killed the kernel went from
# crashing to running in 0.46s). Single-threaded is somewhat slower per BLAS
# call, but the actual matrix sizes here are small enough (~7.8M x ~130) that
# it's still sub-second either way.
import os
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['NUMEXPR_NUM_THREADS'] = '1'
os.environ['MKL_THREADING_LAYER'] = 'SEQUENTIAL'

import pipeline
import networkx as nx
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import count
import time
import pickle
import shutil
import sys
import itertools
from collections import defaultdict
import geopandas as gpd
from tqdm.auto import tqdm
from libpysal.weights import Queen
import esda
import glob, re
from scipy.stats import ks_2samp
import math
from haversine import haversine
from scipy.stats import wasserstein_distance

import plotly.io as pio
pio.renderers.default = "notebook"

seed = 21
interval = '24'
agg = True

if agg:
    if interval == "6":
        fpath = Path('data/agg/DEP_NET_GEOTAX11_14460_20190101_20191231_Tc6_Ts1.csv.gz')
        save_dir = Path(f'data/agg/tests/seed{seed}')
    elif interval == '24':
        fpath = Path('data/agg/geotax_complete_24h.pkl')
        save_dir = Path(f'data/agg/tests/seed{seed}')
    else:
        print("Invalid time range (must be 24 or 6)")
else:
    if interval == "6":
        fpath = Path('data/poi_level/6h/thresholded_networks/0_network.txt')
        save_dir = Path(f'data/poi_level/6h/tests/seed{seed}')
        data = Path('data/poi_level/depnet_undirected.gz')
    elif interval == '24':
        fpath = Path('data/poi_level/24h/0_network_24h.txt')
        save_dir = Path(f'data/poi_level/24h/tests/seed{seed}')
        data = Path('data/poi_level/24h/depnet_undirected_24h.gz')
    else:
        print("Invalid time range (must be 24 or 6)")

save_dir.mkdir(parents=True, exist_ok=True)

print(f"Interval: {interval} hrs | agg={agg} | Seed: {seed}")

Interval: 24 hrs | agg=True | Seed: 21

In [4]:
# set parameters
p, q, dim = 4, 0.25, 128
cat_threshold = 20
controlled = True
weight = 'cov'
if weight:
    weighted = True
else:
    weighted = False
strength = 0.5
feats_id = 'emb_dist'

print(f'weight={weight} (weighted={weighted}) | strength={strength})')

weight=cov (weighted=True) | strength=0.5)

### Test Run Template

In [5]:
# --- new split if needed ---

print(f"Interval: {interval} hrs | agg={agg} | Seed: {seed} | 'Weight: {weight} | Strength: {strength})'")

split_path = save_dir / f"split_{seed}_{weight}_{controlled}.pkl"
train_path = save_dir / f"train_{seed}_{weight}.txt"

if split_path.is_file():
    print(f"Split already exists for seed {seed} weight {weight} controlled {controlled}. Exiting...")
    sys.exit()

G, train_neg, test_pos, test_neg = pipeline.prepare_data(
    fpath, test_frac=.25, seed=seed, weight=weight, agg=agg, meta=True,
    trainfile=train_path, controlled=controlled)

save_dir.mkdir(parents=True, exist_ok=True)
with open(split_path, 'wb') as f:
    pickle.dump((G, train_neg, test_pos, test_neg), f, pickle.HIGHEST_PROTOCOL)
print(f"Saved split at {split_path}")

Interval: 24 hrs | agg=True | Seed: 21 | 'Weight: None | Strength: 0.5)'

Nodes: 15136
Edges: 5229044

sampling non-edges:   0%|          | 0/1307261 [00:00<?, ?edge/s]

sampling non-edges:   0%|          | 0/3921783 [00:00<?, ?edge/s]

Wrote training graph: 15136 nodes, 3921783 edges

Saved split at data\agg\tests\seed21\split_21_None_False.pkl

In [6]:
# --- single test ---

print(f"Interval: {interval} hrs | agg={agg} | Seed: {seed} | 'Weight: {weight} | Strength: {strength})'")

split_path = save_dir / f"split_{seed}_{weight}_{controlled}.pkl"
with open(split_path, 'rb') as f:
    G, train_neg, test_pos, test_neg = pickle.load(f)

feats = ['emb', 'dist']

result = pipeline.run_pipeline(
    save_dir / f"train_{seed}_{weight}.txt", train_neg, test_pos, test_neg, seed=seed,
    p=p, q=q, dim=dim, workers=6, weighted=weighted,
    features=feats, cat_threshold=cat_threshold, G=G,
    agg=agg, strength=strength
)

if strength:
    link_auc, str_auc = result['link_auc'], result['str_auc']
    print(f"Link AUC: {link_auc:.4f} | Strength AUC: {str_auc:.4f}")
    output = pd.Series(result)
else:
    link_auc = result['link_auc']
    print(f"Link AUC: {link_auc:.4f}")
    output = pd.Series(result)

# save both score as txt and full output as pickle
feats_id = '_'.join(feats) if isinstance(feats, list) else feats
out_file = save_dir / f'matching{controlled}/weight_{weight}/strength{strength}-feats_{feats_id}'
out_file.mkdir(parents=True, exist_ok=True)
with open(out_file / 'auc_scores.txt', 'w') as f:
        f.write(str(link_auc) + '\n')
        if strength:
            f.write(str(str_auc))
        print('Score saved.')
with open(out_file / 'output.pkl', 'wb') as f:
     output.to_pickle(f)
     print('Output saved.')

Interval: 24 hrs | agg=True | Seed: 21 | 'Weight: None | Strength: 0.5)'

Notice: pecanpy mode 'PreComp' failed: CPUDispatcher(<function PreComp.preprocess_transition_probs.<locals>.compute_all_transition_probs at 0x000002266E455EE0>) returned a result with an exception set

  0%|          | 0/151270 [00:00<?, ?it/s]

Took 00:03:27.61 to generate walks

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Took 00:00:24.91 to train embeddings
Notice: fell back to 'DenseOTF'
Embeddings generated: 15127 nodes, dim=128

[mem] before building train feature matrices: process RSS=12.66 GiB, system available=13.57 GiB

[mem] after X_train_pos built: process RSS=13.97 GiB, system available=12.83 GiB

[mem] after X_train_neg built: process RSS=2.45 GiB, system available=8.32 GiB

Training matrix: 7838674 samples x 129 features
[mem] after training matrix assembled + originals freed: process RSS=6.56 GiB, system available=18.86 GiB

[mem] after add_constant + consolidating to ndarray, right before Logit(...) construction: process RSS=10.68 GiB, system available=16.26 GiB

[mem] after Logit(...) constructed, right before .fit(): process RSS=10.68 GiB, system available=16.43 GiB

[mem] entered _chunked_logit_hessian (n=7838674, p=130): process RSS=8.29 GiB, system available=14.82 GiB

[mem] finished _chunked_logit_hessian: process RSS=8.30 GiB, system available=14.80 GiB

[mem] after link_model.fit() returned: process RSS=8.24 GiB, system available=14.86 GiB

c:\Users\User\anaconda3\envs\depnet\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

[mem] entered _chunked_logit_hessian (n=7838674, p=1): process RSS=8.37 GiB, system available=14.66 GiB

[mem] finished _chunked_logit_hessian: process RSS=8.37 GiB, system available=14.65 GiB

[mem] entered _chunked_logit_hessian (n=7838674, p=1): process RSS=8.37 GiB, system available=14.66 GiB

[mem] finished _chunked_logit_hessian: process RSS=8.37 GiB, system available=14.66 GiB

                 Coef.  Std.Err.           z  P>|z|     [0.025     0.975]
const        14.457671  0.022667  637.824413    0.0  14.413244  14.502098
log_dist_km  -1.283752  0.002801 -458.365879    0.0  -1.289241  -1.278263

[emb+dist (hadamard)]  Link AUC = 0.9036

Distance-matched strength set: train 854454/3921783, test 284020/1307250 edges kept

[mem] strength head: after consolidating to ndarray, before Logit(...) construction: process RSS=17.48 GiB, system available=8.72 GiB

[mem] strength head: after Logit(...) constructed, right before .fit(): process RSS=17.48 GiB, system available=8.72 GiB

[mem] entered _chunked_logit_hessian (n=854454, p=130): process RSS=17.48 GiB, system available=8.69 GiB

[mem] finished _chunked_logit_hessian: process RSS=17.49 GiB, system available=8.66 GiB

[mem] strength head: after str_model.fit() returned: process RSS=17.48 GiB, system available=8.67 GiB

c:\Users\User\anaconda3\envs\depnet\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

[mem] entered _chunked_logit_hessian (n=854454, p=1): process RSS=17.49 GiB, system available=8.68 GiB

[mem] finished _chunked_logit_hessian: process RSS=17.49 GiB, system available=8.67 GiB

[mem] entered _chunked_logit_hessian (n=854454, p=1): process RSS=17.49 GiB, system available=8.68 GiB

[mem] finished _chunked_logit_hessian: process RSS=17.49 GiB, system available=8.67 GiB

                Coef.  Std.Err.           z  P>|z|    [0.025    0.975]
const       -8.784842  0.071100 -123.556060    0.0 -8.924195 -8.645488
log_dist_km -0.243260  0.004711  -51.637606    0.0 -0.252493 -0.234027

[emb+dist (hadamard)]  Strength AUC = 0.8206
Link AUC: 0.9036 | Strength AUC: 0.8206
Score saved.

Output saved.

In [ ]:
# --- comprehensive test ---

print(f"Interval: {interval} hrs | agg={agg} | Seed: {seed}")

file_path = save_dir / f"split_{seed}_{weight}.pkl"
with open(file_path, 'rb') as f:
            G, train_neg, test_pos, test_neg = pickle.load(f)
            
feats_list = [
        ['time'],
        ['comm'],
        ['income'],
        ['time', 'income'],
        ['dist'],
        ['dist', 'time'],
        ['dist', 'income'],
        ['dist', 'time', 'income'],
        ['dist', 'comm', 'time', 'income'],
        ['emb', 'dist'],
        ['emb', 'time'],
        ['emb', 'income'],
        ['emb', 'comm', 'time', 'income'],
        'all'
]

results = {}
for feats in feats_list:
        print(f'NOW TESTING: {feats}')
        auc, _, strength_auc = pipeline.run_pipeline(save_dir / f"train_{seed}_{weight}.txt", 
                                        train_neg, test_pos, test_neg, seed=seed,
                                        p=p, q=q, dim=192, workers=6, weighted=weighted,
                                        features=feats, cat_threshold=cat_threshold, G=G,
                                        agg=agg, embedding_map=emb_map, strength=strength)

        feats_id = '_'.join(feats) if isinstance(feats, list) else feats
        results[feats_id] = (auc, strength_auc)

with open(save_dir / f'weight_{weight}/w{weight}-strength{strength}_comprehensive.txt', 'w') as f:
        for f_id, result in results.items():
                auc, strength_auc = result
                f.write(f'Result for features: {f_id} -> AUC: {auc:.6f} | Strength AUC: {strength_auc:.6f}\n')

print('All scores saved.')

### Distance-Controlled Negative Edge Sampling

In [ ]:
# Plots/Verification

from pipeline import distribution_finder, sample_non_edges_dist_controlled, sample_non_edges_agg_stratified, load
print(f"Interval: {interval} hrs | agg={agg} | Seed: {seed}")

# Generate the sample 
if agg == False:
    G = load('data/undir_trials/thresholded_networks/0_network.txt')
    distrs, sets = distribution_finder(G, bins=50)
    dist_distr = distrs[0]
    sample = sample_non_edges_dist_controlled(G, dist_distr, len(list(G.nodes())) // 2)
    original_distances = list(nx.get_edge_attributes(G, 'DIST_KM').values())
else:
    with open(fpath, 'rb') as f:
        G = pickle.load(f)
    distrs, sets = distribution_finder(G, bins=50)
    dist_distr = distrs[0]
    sample = sample_non_edges_dist_controlled(G, dist_distr, len(list(G.nodes())) // 2)
    #sample = sample_non_edges_agg_stratified(G, len(list(G.nodes())) // 2)
    original_distances = [d for d in nx.get_edge_attributes(G, 'DIST_KM').values() 
                      if d is not None and not math.isnan(d)]

locs = []
for u, v in sample:
    lat_u, lon_u = G.nodes[u]['latitude'], G.nodes[u]['longitude']
    lat_v, lon_v = G.nodes[v]['latitude'], G.nodes[v]['longitude']
    locs.append((lat_u, lon_u, lat_v, lon_v))

sampled_distances = [haversine((lat1, lon1), (lat2, lon2)) for (lat1, lon1, lat2, lon2) in locs]

fig, axes = plt.subplots(1, 2, figsize=(12, 4), sharex=True, sharey=True)
pd.Series(original_distances).plot.kde(bw_method='scott', ax=axes[0], title='Original Edges: Distance', color='blue')
pd.Series(sampled_distances).plot.kde(bw_method='scott', ax=axes[1], title='Sampled Non-Edges: Distance', color='orange')
axes[0].set_xlabel('Distance (KM)')
axes[1].set_xlabel('Distance (KM)')
axes[0].set_xlim(left=0)
axes[1].set_ylim(bottom=0)
plt.tight_layout()
#plt.savefig(r'data\undir_trials\imgs\distance_distr_comp.png')
plt.show()

# wasserstein distance
print(f'Wasserstein Distance: {wasserstein_distance(original_distances, sampled_distances):.4f}')

In [ ]:
# Re-running pipeline

# --- prep ---
fpath = Path(r'data/undir_trials/thresholded_networks/0_network.txt')
G, train_neg, test_pos, test_neg = pipeline.prepare_data(fpath)

# --- metadata only ---
auc_geo, _ = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['geo'])
auc_cat, _ = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['cat'])
auc_vis, _ = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['visits'])
auc_geo_cat, _ = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['geo', 'cat'])
auc_all_metadata, _ = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['geo', 'cat', 'visits'])

# --- embeddings only ---
auc_emb, emb_map = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['emb'])

# --- embeddings + metadata ---
auc_emb_geo, _ = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['emb', 'geo'], embedding_map=emb_map)
auc_emb_geo_cat, _ = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['emb', 'geo', 'cat'], embedding_map=emb_map)
auc_all, _ = pipeline.run_pipeline('train.txt', train_neg, test_pos, test_neg, G=G, features=['emb', 'geo', 'cat', 'visits'], embedding_map=emb_map)

# --- results table ---
results = [
    (['geo'],                          auc_geo),
    (['cat'],                          auc_cat),
    (['visits'],                       auc_vis),
    (['geo', 'cat'],                   auc_geo_cat),
    (['geo', 'cat', 'visits'],         auc_all_metadata),
    (['emb'],                          auc_emb),
    (['emb', 'geo'],                   auc_emb_geo),
    (['emb', 'geo', 'cat'],            auc_emb_geo_cat),
    (['emb', 'geo', 'cat', 'visits'],  auc_all),
]

df_results = pd.DataFrame(results, columns=['Features', 'AUC'])
df_results['Features'] = df_results['Features'].apply(lambda x: ' + '.join(x))
df_results['AUC'] = df_results['AUC'].round(4)

# flag embedding inclusion
df_results['Includes_Emb'] = df_results['Features'].str.contains('emb').map({True: 'with_emb', False: 'without_emb'})

In [ ]:
# AUC bar plot color-coded by embedding inclusion
plt.figure(figsize=(10, 6))
sns.barplot(data=df_results, x='AUC', y='Features', hue='Includes_Emb', dodge=False, palette={'with_emb':'tab:blue','without_emb':'tab:green'})
plt.title('AUC Scores by Feature Set (Distance-Controlled Negative Sampling)')
plt.xlabel('AUC')
plt.ylabel('Feature Set')
plt.xlim(left=0.5, right=1)
for i, value in enumerate(df_results['AUC']):
    plt.text(value + 0.001, i, f"{value:.4f}", va='center')
plt.legend(title='Includes Embedding')
plt.tight_layout()
plt.savefig('data/undir_trials/imgs/auc_by_feature_barplot.png')
plt.show()

# Agg Network

In [5]:
# --- initial setup ---

# bring in network as both nx.Graph and dataframe
_dtypes = {
    'NODE_A': 'category', 'NODE_B': 'category',
    'N_COVISITS': 'float32', 'DIST_KM_MIN': 'float32',
    'DIST_KM_MEAN': 'float32', 'N_UIDS_A': 'float32',
    'N_POIS_A': 'float32', 'N_VISITS_A': 'float32',
    'N_UIDS_B': 'float32', 'N_POIS_B': 'float32', 
    'N_VISITS_B': 'float32', 'DEP': 'float32'
}
G = pipeline.load(fpath)
if str(fpath).endswith('.pkl'):
    with open(fpath, 'rb') as f:
        agg_df = pickle.load(f)
else:
    agg_df = pd.read_csv(fpath, dtype=_dtypes)

# list possible combos and permutations (sets prevent double-counting)
cats = set()
tracts = set()
for n in G.nodes():
    c, t = n.split('_')
    cats.add(c)
    tracts.add(t)
combos = list(itertools.combinations(sorted(cats), 2))
perms = list(itertools.permutations(cats, 2))

cat_to_idx = {cat: i for i, cat in enumerate(cats)}

def return_results(path, _return=None, include_str=False):
    with open(path / 'output.pkl', 'rb') as f:
        output = pickle.load(f)
        if include_str and len(output) < 6:
            print('File has no strength results. Falling back to link.')
            include_str=False
        if _return == 'auc':
            return output[['link_auc', 'str_auc']].tolist() if include_str else output['link_auc']
        elif _return == 'model':
            return output[['link_model', 'link_cm', 'str_model', 'str_cm']].tolist() \
            if include_str else output[['link_model', 'link_cm']].tolist()
        else:
            return output

Nodes: 15136
Edges: 5229044

### Basic Analyses

In [ ]:
# --- DEP distribution (descriptive) ---

dep_vals = np.array([d for d in nx.get_edge_attributes(G, 'DEP').values() if d is not None])

print(f"Edges with DEP: {len(dep_vals)}")
print(pd.Series(dep_vals).describe())
n_zero = int((dep_vals == 0).sum())
print(f"Zero-DEP edges: {n_zero} ({n_zero / len(dep_vals):.2%})")

# histogram on log-x (DEP values are tiny and heavily right-skewed)
pos = dep_vals[dep_vals > 0]
fig, ax = plt.subplots(figsize=(8, 5))
ax.hist(pos, bins=np.logspace(np.log10(pos.min()), np.log10(pos.max()), 50),
        color='steelblue', alpha=0.7, edgecolor='white')
ax.set_xscale('log')
ax.axvline(np.median(pos), color='crimson', linestyle='--', linewidth=1.3,
           label=f'median = {np.median(pos):.2e}')
ax.set_xlabel('DEP')
ax.set_ylabel('Number of edges')
ax.set_title('Agg Network: DEP Distribution')
ax.legend()
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.savefig('imgs/agg/dep_distribution.png', dpi=300)
plt.show()

# --- concentration / inequality of total DEP (weighting sanity check) ---
# how much of the total edge weight (DEP) a top fraction of edges accounts for.
# high concentration => DEP-weighted walks are dominated by a few edges.

total_dep = dep_vals.sum()
desc = np.sort(dep_vals)[::-1]                 # descending
cum_share_top = np.cumsum(desc) / total_dep    # share of total DEP held by top-k edges
n = len(dep_vals)

print("\nShare of total DEP accounted for by the top fraction of edges:")
for q in [0.01, 0.05, 0.10, 0.25, 0.50]:
    k = max(1, int(round(q * n)))
    print(f"  top {q:>4.0%} of edges  ->  {cum_share_top[k-1]:6.1%} of total DEP")

# Gini coefficient (0 = perfectly equal, 1 = maximally concentrated)
asc = np.sort(dep_vals)
cum = np.cumsum(asc)
gini = (n + 1 - 2 * (cum.sum() / cum[-1])) / n
print(f"\nGini coefficient of DEP: {gini:.3f}")

# Lorenz curve
lorenz = np.insert(cum / cum[-1], 0, 0)
x = np.linspace(0, 1, len(lorenz))

fig, ax = plt.subplots(figsize=(6, 6))
ax.plot(x, lorenz, color='steelblue', linewidth=1.8, label=f'Lorenz (Gini = {gini:.3f})')
ax.plot([0, 1], [0, 1], color='gray', linestyle='--', linewidth=1, label='perfect equality')
ax.fill_between(x, lorenz, x, alpha=0.15, color='steelblue')
ax.set_xlabel('Cumulative share of edges')
ax.set_ylabel('Cumulative share of total DEP')
ax.set_title('DEP Concentration (Lorenz Curve)')
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
ax.legend(loc='upper left')
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.savefig('imgs/agg/dep_lorenz.png', dpi=300)
plt.show()

In [ ]:
# === check proportion of possible within-tract edges that actually exist ===

realization_rates = []
for t in tracts:
    nodes_in_tract = set(n for n in G.nodes() if t in n)
    # subgraph creates only the edges that exist between cats within the tract
    edges_in_tract = G.subgraph(nodes_in_tract).number_of_edges()
    rr = (edges_in_tract / len(combos)) * 100
    realization_rates.append([t, rr, edges_in_tract])
rr_df = pd.DataFrame(realization_rates, columns=['tract', 'rate', 'total'])

print(f'total within-tract edges: {rr_df["total"].sum()}')
print(rr_df['rate'].describe())

# --- kde plot ---

sns.set_theme(style="whitegrid")
plt.figure(figsize=(8, 5))
# stat="density" normalizes the histogram
sns.histplot(data=rr_df, x="rate", bins=20, kde=True, color="teal", alpha=0.6, stat="density")

plt.suptitle(
    "Realization Rate Distribution\n(bucket size relative to max)",
    fontsize=14,
    x=0.5,
    ha='center'
)
plt.xlabel("Realization Rate (%)", fontsize=12, x=0.45)
plt.ylabel("Density", fontsize=12)
plt.xlim(0)
plt.tight_layout()
plt.savefig('imgs/agg/rr_dist.png', dpi=500)
plt.close()
print('KDE plot saved.')

In [ ]:
# -- barchart: shrinkage-regularized dependency per category pair ---
#
# Low-traffic pairs are inflated by the covisits>=1 floor: DEP >= 1/(v_i*v_j), which is
# large when the visit-product denominator is small. Neither pooling nor a threshold
# fixes it, because a uniformly low-traffic category (e.g. Agriculture) has no high-
# support edges to lean on. Empirical-Bayes shrinkage pulls each rate toward the global
# rate r0 by an amount set by its support (v_i*v_j):
#     DEP_shrunk = (covisits + alpha*r0) / (v_i*v_j + alpha)
# alpha = pseudo-exposure (same units as v_i*v_j): the traffic level at which the data
# starts to outweigh the prior. We POOL each category pair first, then shrink once with
# its TOTAL support, so a pair backed by few low-traffic edges collapses to r0 and can't
# top the ranking.

# load network if needed
if 'G' not in globals():
    with open(fpath, 'rb') as f:
        G = pickle.load(f)

# --- one pass: per-edge covisits, denominator (visit-product), and category pair ---
cov_list, den_list, pair_list = [], [], []
for u, v, data in G.edges(data=True):
    c1, c2 = u.split('||')[0], v.split('||')[0]
    if c1 == c2:
        continue
    cov = data.get('N_COVISITS')
    vi = G.nodes[u].get('total_visits')
    vj = G.nodes[v].get('total_visits')
    if cov is None or vi is None or vj is None:
        continue
    cov_list.append(cov)
    den_list.append(vi * vj)
    pair_list.append(f"{c1} — {c2}" if c1 <= c2 else f"{c2} — {c1}")

edf = pd.DataFrame({'pair': pair_list,
                    'cov': np.asarray(cov_list, dtype='float64'),
                    'den': np.asarray(den_list, dtype='float64')})
edf['dep_raw'] = edf['cov'] / edf['den']

# global baseline rate r0 = pooled covisit rate across the whole network
r0 = edf['cov'].sum() / edf['den'].sum()
print(f"{edf['pair'].nunique()} category pairs | {len(edf):,} cross-category edges")
print(f"global baseline rate r0 = {r0:.3e}")

# --- diagnostic: is the inflation really driven by low support (small v_i*v_j)? ---
pct = [10, 25, 50, 75, 90]
den_pctiles = np.percentile(edf['den'], pct)
global_med_den = edf['den'].median()
print("\nedge denominator (v_i*v_j) percentiles: "
      + ", ".join(f"p{p}={v:.2e}" for p, v in zip(pct, den_pctiles)))

raw_top = (edf.groupby('pair')
           .agg(dep_raw=('dep_raw', 'mean'), med_den=('den', 'median'), n_edges=('cov', 'size'))
           .sort_values('dep_raw', ascending=False))
print(f"\ncurrent top-8 pairs by raw mean DEP â€” median denom vs global median ({global_med_den:.2e}):")
for pair, row in raw_top.head(8).iterrows():
    print(f"  {pair:<42} med_den={row['med_den']:.2e} ({row['med_den']/global_med_den:5.2f}x global)  n={int(row['n_edges'])}")

# --- pool each pair, THEN shrink once, using the pair's total support (Sum den) ---
# Shrinking per-edge then averaging leaves the pair-level estimate itself low-support
# (a mean over few edges), so small-n pairs leak back in. Pooling first means alpha
# acts on each pair's total Sum(v_i*v_j): tiny-support pairs collapse to r0.
pair_tot = edf.groupby('pair').agg(cov=('cov', 'sum'), den=('den', 'sum'), n_edges=('cov', 'size'))
pair_tot['pooled_raw'] = pair_tot['cov'] / pair_tot['den']

# alpha now lives on the scale of the per-pair TOTAL denominator
tot_pctiles = np.percentile(pair_tot['den'], pct)

def pooled_shrunk(alpha):
    return (pair_tot['cov'] + alpha * r0) / (pair_tot['den'] + alpha)

sweep_alphas = {'p25': tot_pctiles[1], 'p50': tot_pctiles[2],
                'p75': tot_pctiles[3], '3x_p50': 3 * tot_pctiles[2]}
print("\nalpha sweep â€” top 6 pairs by pool-then-shrink DEP  (n_edges in parens):")
for name, alpha in sweep_alphas.items():
    print(f"\n  alpha = {name} ({alpha:.2e}):")
    for pair, val in pooled_shrunk(alpha).sort_values(ascending=False).head(6).items():
        print(f"    {pair:<42} {val:.3e}  (n={int(pair_tot.loc[pair, 'n_edges'])})")

# --- chosen alpha for the plotted barchart (tune from the sweep above) ---
ALPHA = tot_pctiles[2]  # median per-pair total denominator
combo_stats = (pair_tot
               .assign(shrunk_dep=pooled_shrunk(ALPHA), raw_dep=pair_tot['pooled_raw'])
               .sort_values('shrunk_dep', ascending=False)
               .reset_index()[['pair', 'shrunk_dep', 'raw_dep', 'n_edges']])

print(f"\nplotting with ALPHA = {ALPHA:.3e}")
print(combo_stats.head(15).to_string(index=False))

# === top 20 bar chart, colored by edge support ===
top20 = combo_stats.head(20).copy()

fig, ax = plt.subplots(figsize=(9, 7))
norm = plt.Normalize(top20['n_edges'].min(), top20['n_edges'].max())
colors = [plt.cm.Blues(norm(v)) for v in top20['n_edges'].values[::-1]]
ax.barh(range(len(top20)), top20['shrunk_dep'].values[::-1], color=colors, alpha=0.9)
ax.set_yticks(range(len(top20)))
ax.set_yticklabels(top20['pair'].values[::-1], fontsize=9)
ax.set_xlabel('Shrinkage-regularized DEP  (pool-then-shrink)', fontsize=11)
ax.set_title(f'Top 20 Category Pairs by Regularized Dependency',
             fontsize=12, fontweight='bold')
ax.spines[['top', 'right']].set_visible(False)

sm = plt.cm.ScalarMappable(cmap=plt.cm.Blues, norm=norm)
sm.set_array([])
fig.colorbar(sm, ax=ax, label='# edges', shrink=0.6)

plt.tight_layout()
plt.savefig('imgs/agg/perm_dep_top20.png', dpi=300, bbox_inches='tight')
plt.show()

### Prediction Results

AUC Barplots

In [6]:
print(f"Interval: {interval} hrs | agg={agg} | Seed: {seed} | 'Weight: {weight} | Strength: {strength})'")

# dist-controlling + weightedness | 4 bars

dm_w_auc, str_dm_w_auc = return_results(save_dir / f'matchingTrue/weight_{weight}/strength{strength}-feats_{feats_id}', _return='auc', include_str=True)
dm_u_auc, str_dm_u_auc = return_results(save_dir / f'matchingTrue/weight_None/strength{strength}-feats_{feats_id}', _return='auc', include_str=True)
um_w_auc, str_um_w_auc = return_results(save_dir / f'matchingFalse/weight_{weight}/strength{strength}-feats_{feats_id}', _return='auc', include_str=True)
um_u_auc, str_um_u_auc = return_results(save_dir / f'matchingFalse/weight_None/strength{strength}-feats_{feats_id}', _return='auc', include_str=True)

categories = ['Distance-Matched | Weighted',
              'Distance-Matched | Unweighted',
              'Unmatched | Weighted',
              'Unmatched | Unweighted']
values = [dm_w_auc, dm_u_auc, um_w_auc, um_u_auc]

# create plot

fig, ax = plt.subplots()
color_order = ['navy', 'skyblue', 'crimson', 'pink']
ax.barh(categories, values, color=color_order, height=0.6)
ax.invert_yaxis()
ax.set_xlim(0.5)
ax.set_xlabel('AUC')
ax.set_title(f'Link Prediction AUC: Distance-Matching x Weightedness (Weight={weight.upper()})')
plt.tight_layout()
plt.savefig('figures/prediction_results/linkpred-distmatch_weightedness_sweep.png')

# --- same for strength (just in case) ---

categories = ['Distance-Matched | Weighted',
              'Distance-Matched | Unweighted',
              'Unmatched | Weighted',
              'Unmatched | Unweighted']
values = [str_dm_w_auc, str_dm_u_auc, str_um_w_auc, str_um_u_auc]

fig, ax = plt.subplots()
color_order = ['navy', 'skyblue', 'crimson', 'pink']
ax.barh(categories, values, color=color_order, height=0.6)
ax.invert_yaxis()
ax.set_xlim(0.5)
ax.set_xlabel('AUC')
ax.set_title(f'Strength Prediction AUC: Distance-Matching x Weightedness (Weight={weight.upper()})')
plt.tight_layout()
plt.savefig('figures/prediction_results/strpred-distmatch_weightedness_sweep.png')

Interval: 24 hrs | agg=True | Seed: 21 | 'Weight: cov | Strength: 0.5)'

In [7]:
# --- 4-panel link prediction results: weighted/unweighted x all/strong links ---

def load_strength_scores(wtag):
    """feat -> (all_links_auc, strong_links_auc) for a given network weight."""
    d = f"data/agg/tests/seed{seed}/weight_{wtag}"
    scores = {}
    # comprehensive file first (per-feature files below override it)
    for path in glob.glob(os.path.join(d, f"strength{strength}_comprehensive.txt")):
        with open(path) as f:
            for line in f:
                m = re.search(r"features:\s*(\S+)\s*->\s*AUC:\s*([\d.]+)\s*\|\s*Strength AUC:\s*([\d.]+)", line)
                if m:
                    scores[m.group(1)] = (float(m.group(2)), float(m.group(3)))
    # per-feature files (includes the emb-only results)
    for path in glob.glob(os.path.join(d, f"w{wtag}-strength{strength}-feats_*.txt")):
        m = re.search(r"feats_(.+)\.txt$", os.path.basename(path))
        if not m:
            continue
        lines = [ln.strip() for ln in open(path) if ln.strip()]
        if len(lines) >= 2:
            scores[m.group(1)] = (float(lines[0]), float(lines[1]))
    return scores

# cool for unweighted, warm for weighted; same shade across both rows
columns = [
    ("Unweighted", load_strength_scores(None), "#09946A"),
    (f"Weighted ({weight.upper()})", load_strength_scores({weight}), "#b31f6b"),
]
rows = [
    ("All links", 0),     # line 1 -> link-prediction AUC
    ("Strong links", 1),  # line 2 -> strong-vs-weak AUC
]

fig, axes = plt.subplots(2, 2, figsize=(14, 12))
for c, (col_label, scores, color) in enumerate(columns):
    # fix feature order by all-links AUC; strong-links row reuses it
    order = sorted(scores, key=lambda f: scores[f][0])
    for r, (row_label, idx) in enumerate(rows):
        ax = axes[r, c]
        labels = [f.replace("_", "+") for f in order]
        values = [scores[f][idx] for f in order]
        bars = ax.barh(labels, values, color=color, edgecolor="white")
        ax.bar_label(bars, fmt="%.3f", padding=3, fontsize=8)
        ax.set_xlabel("AUC")
        ax.set_title(f"{row_label} — {col_label}")
        ax.set_xlim(0.5, 1.0)
        ax.spines[["top", "right"]].set_visible(False)
        ax.invert_yaxis()

fig.suptitle(f"Link Prediction AUC by Feature Set (Agg Network, seed={seed})", fontsize=14)
plt.tight_layout()
plt.savefig(f"imgs/agg/link_pred_auc_4panel_s{seed}_strength{strength}.png", dpi=150)
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'imgs/agg/link_pred_auc_4panel_s21_strength0.5.png'

Regression Table + Error Analysis

In [7]:
import gc

print(f"Interval: {interval} hrs | agg={agg} | Seed: {seed} | 'Weight: {weight} | Strength: {strength})'")


def prepare_table(model, cm, threshold=0.5):
    """
    Full reporting bundle for a fitted statsmodels Logit result.

    NOTE (fixed 2026-09-01): originally used
    pd.read_html(model.summary().tables[1].as_html(), ...), which requires
    lxml -- not installed in this env, so it crashed here. summary2().tables[1]
    is already a plain DataFrame, no HTML round-trip needed. Also,
    model.conf_int() returns a bare ndarray (not a labeled DataFrame) here,
    because pipeline.py passes a plain ndarray into sm.Logit() and manually
    restores names via model.data.xnames afterward (a fix for a separate
    memory bug) -- this bypasses statsmodels' normal pandas metadata
    plumbing, so conf_int() must be indexed positionally, not by column
    label 0/1.

    Returns
    -------
    dict with keys:
        'coef_table'        - per-feature coefficients, odds ratios, CIs
        'embedding_coefs'   - same but for embedding dimensions
        'diagnostics'       - model-level fit statistics
        'confusion_matrix'  - test-set counts, as computed in pipeline.run_pipeline
        'confusion_metrics' - accuracy/precision/recall/etc derived from it
    """
    coef_df = model.summary2().tables[1].copy()
    ci = model.conf_int()
    if hasattr(ci, 'to_numpy'):
        ci_low, ci_high = ci[0].to_numpy(), ci[1].to_numpy()
    else:
        ci_low, ci_high = ci[:, 0], ci[:, 1]
    coef_df['Odds Ratio'] = np.exp(model.params)
    coef_df['OR 95% CI Low'] = np.exp(ci_low)
    coef_df['OR 95% CI High'] = np.exp(ci_high)
    coef_df = coef_df[['Coef.', 'Std.Err.', 'z', 'P>|z|', '[0.025', '0.975]',
                        'Odds Ratio', 'OR 95% CI Low', 'OR 95% CI High']]

    is_emb = coef_df.index.str.startswith('emb_')
    embedding_coefs = coef_df[is_emb]
    coef_df = coef_df[~is_emb]

    mle = model.mle_retvals
    diagnostics = pd.Series({
        'Dependent Variable': model.model.endog_names,
        'No. Observations': int(model.nobs),
        'Df Model': model.df_model,
        'Df Residuals': model.df_resid,
        'Converged': mle.get('converged'),
        'Iterations': mle.get('iterations'),
        'Covariance Type': model.cov_type,
        'Log-Likelihood': model.llf,
        'LL-Null (intercept only)': model.llnull,
        'LLR chi2': model.llr,
        'LLR p-value': model.llr_pvalue,
        "Pseudo R-squ. (McFadden's)": model.prsquared,
        'AIC': model.aic,
        'BIC': model.bic,
    }, name='Value').to_frame()
    diagnostics['Value'] = diagnostics['Value'].apply(
        lambda v: round(v, 4) if isinstance(v, float) else v)

    confusion_matrix = pd.DataFrame(
        cm, index=['Actual: -', 'Actual: +'],
        columns=['Predicted: -', 'Predicted: +']
    )

    tn, fp, fn, tp = cm[0, 0], cm[0, 1], cm[1, 0], cm[1, 1]
    total = tn + fp + fn + tp
    confusion_metrics = pd.Series({
        'Threshold': threshold,
        'Accuracy': (tp + tn) / total,
        'Precision': tp / (tp + fp) if (tp + fp) else np.nan,
        'Recall (Sensitivity)': tp / (tp + fn) if (tp + fn) else np.nan,
        'Specificity': tn / (tn + fp) if (tn + fp) else np.nan,
        'F1': (2 * tp) / (2 * tp + fp + fn) if (2 * tp + fp + fn) else np.nan,
    }, name='Value').to_frame()

    return {
        'coef_table': coef_df.round(4),
        'embedding_coefs': embedding_coefs.round(4),
        'diagnostics': diagnostics,
        'confusion_matrix': confusion_matrix,
        'confusion_metrics': confusion_metrics.round(4),
    }


# NOTE (fixed 2026-09-01): each combo's output.pkl is ~9 GB once unpickled
# (statsmodels results objects retain the full design matrix internally).
# Loading all 4 combos' full models simultaneously (the original approach)
# needs ~36 GB and MemoryErrors on this 31.7 GB machine. Instead, process
# one combo fully (build its small summary tables via prepare_table) and
# explicitly drop the big model objects before moving to the next combo.
combo_paths = {
    'Distance-Matched | Weighted': save_dir / f'matchingTrue/weight_{weight}/strength{strength}-feats_{feats_id}',
    'Distance-Matched | Unweighted': save_dir / f'matchingTrue/weight_None/strength{strength}-feats_{feats_id}',
    'Unmatched | Weighted': save_dir / f'matchingFalse/weight_{weight}/strength{strength}-feats_{feats_id}',
    'Unmatched | Unweighted': save_dir / f'matchingFalse/weight_None/strength{strength}-feats_{feats_id}',
}

tables = {}
for label, path in combo_paths.items():
    link_m, link_cm, str_m, str_cm = return_results(path, _return='model', include_str=True)
    tables[(label, 'link')] = prepare_table(link_m, link_cm)
    tables[(label, 'strength')] = prepare_table(str_m, str_cm)
    del link_m, link_cm, str_m, str_cm
    gc.collect()
    print(f"Processed: {label}")

Interval: 24 hrs | agg=True | Seed: 21 | 'Weight: cov | Strength: 0.5)'

Processed: Distance-Matched | Weighted

Processed: Distance-Matched | Unweighted

Processed: Unmatched | Weighted

Processed: Unmatched | Unweighted

In [8]:
from IPython.display import display

for label in combo_paths:
    print(f"\n{'='*10}\n{label} - Link Model\n{'='*10}")
    for name, tbl in tables[(label, 'link')].items():
        print(f"-- {name} --")
        display(tbl)

for label in combo_paths:
    print(f"\n{'-'*10}\n{label} - Strength Model\n{'-'*10}")
    for name, tbl in tables[(label, 'strength')].items():
        print(f"-- {name} --")
        display(tbl)

==========
Distance-Matched | Weighted - Link Model
==========
-- coef_table --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
const,-3.9805,0.0073,-545.4033,0.0,-3.9948,-3.9662,0.0187,0.0184,0.0189
log_dist_km,0.5509,0.0019,297.7725,0.0,0.5473,0.5545,1.7348,1.7285,1.7411

-- embedding_coefs --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
emb_hadamard_0,0.6192,0.0236,26.2812,0.0,0.5731,0.6654,1.8575,1.7737,1.9453
emb_hadamard_1,0.6271,0.0196,32.0030,0.0,0.5887,0.6656,1.8723,1.8017,1.9456
emb_hadamard_2,1.7541,0.0254,69.0003,0.0,1.7042,1.8039,5.7781,5.4972,6.0733
emb_hadamard_3,0.2199,0.0153,14.3632,0.0,0.1899,0.2499,1.2459,1.2091,1.2839
emb_hadamard_4,0.8268,0.0161,51.4261,0.0,0.7953,0.8583,2.2859,2.2150,2.3591
...,...,...,...,...,...,...,...,...,...
emb_hadamard_123,2.3809,0.0161,148.0712,0.0,2.3494,2.4124,10.8144,10.4789,11.1606
emb_hadamard_124,1.2746,0.0255,49.9638,0.0,1.2246,1.3246,3.5772,3.4027,3.7606
emb_hadamard_125,1.5400,0.0190,80.9135,0.0,1.5027,1.5773,4.6645,4.4937,4.8418
emb_hadamard_126,1.0977,0.0162,67.9211,0.0,1.0660,1.1293,2.9971,2.9037,3.0936
emb_hadamard_127,0.5545,0.0251,22.0583,0.0,0.5053,0.6038,1.7411,1.6574,1.8291

-- diagnostics --

                                   Value
Dependent Variable                     y
No. Observations                 7774315
Df Model                           129.0
Df Residuals                   7774185.0
Converged                           True
Iterations                           128
Covariance Type                nonrobust
Log-Likelihood             -4732679.9774
LL-Null (intercept only)   -5388436.0866
LLR chi2                    1311512.2184
LLR p-value                          0.0
Pseudo R-squ. (McFadden's)        0.1217
AIC                         9465619.9548
BIC                         9467422.5784

-- confusion_matrix --

           Predicted: -  Predicted: +
Actual: -        909140        396336
Actual: +        480266        826984

-- confusion_metrics --

                       Value
Threshold             0.5000
Accuracy              0.6645
Precision             0.6760
Recall (Sensitivity)  0.6326
Specificity           0.6964
F1                    0.6536

==========
Distance-Matched | Unweighted - Link Model
==========
-- coef_table --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
const,6.3051,0.0188,335.4888,0.0000,6.2683,6.3419,547.3594,527.5641,567.8974
log_dist_km,-0.0036,0.0018,-2.0126,0.0442,-0.0071,-0.0001,0.9964,0.9929,0.9999

-- embedding_coefs --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
emb_hadamard_0,5.6770,0.2194,25.8702,0.0000,5.2469,6.1071,2.920721e+02,1.899770e+02,4.490338e+02
emb_hadamard_1,11.7117,0.1962,59.7023,0.0000,11.3273,12.0962,1.219966e+05,8.305546e+04,1.791956e+05
emb_hadamard_2,13.7429,0.1972,69.7040,0.0000,13.3565,14.1294,9.299952e+05,6.319120e+05,1.368689e+06
emb_hadamard_3,3.2959,0.2760,11.9417,0.0000,2.7550,3.8369,2.700300e+01,1.572090e+01,4.638160e+01
emb_hadamard_4,10.9172,0.3687,29.6098,0.0000,10.1945,11.6398,5.511392e+04,2.675606e+04,1.135274e+05
...,...,...,...,...,...,...,...,...,...
emb_hadamard_123,13.8760,0.3315,41.8590,0.0000,13.2262,14.5257,1.062312e+06,5.547338e+05,2.034321e+06
emb_hadamard_124,0.1869,0.3970,0.4708,0.6378,-0.5912,0.9650,1.205500e+00,5.537000e-01,2.624700e+00
emb_hadamard_125,-9.2361,0.1890,-48.8632,0.0000,-9.6066,-8.8656,1.000000e-04,1.000000e-04,1.000000e-04
emb_hadamard_126,14.3711,0.2025,70.9738,0.0000,13.9742,14.7680,1.742985e+06,1.172028e+06,2.592083e+06
emb_hadamard_127,13.2092,0.1742,75.8336,0.0000,12.8678,13.5506,5.453673e+05,3.876332e+05,7.672859e+05

-- diagnostics --

                                   Value
Dependent Variable                     y
No. Observations                 7774315
Df Model                           129.0
Df Residuals                   7774185.0
Converged                          False
Iterations                           200
Covariance Type                nonrobust
Log-Likelihood             -4083722.6281
LL-Null (intercept only)   -5388436.0866
LLR chi2                     2609426.917
LLR p-value                          0.0
Pseudo R-squ. (McFadden's)        0.2421
AIC                         8167705.2562
BIC                         8169507.8799

-- confusion_matrix --

           Predicted: -  Predicted: +
Actual: -        961290        344186
Actual: +        330968        976282

-- confusion_metrics --

                       Value
Threshold             0.5000
Accuracy              0.7416
Precision             0.7393
Recall (Sensitivity)  0.7468
Specificity           0.7364
F1                    0.7431

==========
Unmatched | Weighted - Link Model
==========
-- coef_table --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
const,-0.5972,0.0103,-58.0437,0.0,-0.6173,-0.5770,0.5504,0.5394,0.5616
log_dist_km,-0.6363,0.0025,-256.6290,0.0,-0.6412,-0.6314,0.5292,0.5267,0.5318

-- embedding_coefs --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
emb_hadamard_0,2.3447,0.0278,84.4497,0.0000,2.2903,2.3991,10.4300,9.8776,11.0133
emb_hadamard_1,0.5065,0.0294,17.2267,0.0000,0.4489,0.5641,1.6595,1.5666,1.7579
emb_hadamard_2,0.6263,0.0110,56.8232,0.0000,0.6047,0.6479,1.8707,1.8307,1.9116
emb_hadamard_3,0.6032,0.0236,25.5951,0.0000,0.5570,0.6494,1.8279,1.7454,1.9143
emb_hadamard_4,-0.0427,0.0279,-1.5282,0.1265,-0.0974,0.0121,0.9582,0.9072,1.0121
...,...,...,...,...,...,...,...,...,...
emb_hadamard_123,2.4570,0.0151,162.5683,0.0000,2.4273,2.4866,11.6693,11.3288,12.0202
emb_hadamard_124,-1.1074,0.0275,-40.2919,0.0000,-1.1613,-1.0535,0.3304,0.3131,0.3487
emb_hadamard_125,0.2282,0.0282,8.0837,0.0000,0.1729,0.2836,1.2564,1.1887,1.3279
emb_hadamard_126,-1.3133,0.0258,-50.9152,0.0000,-1.3638,-1.2627,0.2689,0.2557,0.2829
emb_hadamard_127,0.9892,0.0276,35.8104,0.0000,0.9350,1.0433,2.6890,2.5473,2.8386

-- diagnostics --

                                   Value
Dependent Variable                     y
No. Observations                 7838674
Df Model                           129.0
Df Residuals                   7838544.0
Converged                           True
Iterations                            82
Covariance Type                nonrobust
Log-Likelihood             -3681298.7808
LL-Null (intercept only)   -5433353.2559
LLR chi2                    3504108.9503
LLR p-value                          0.0
Pseudo R-squ. (McFadden's)        0.3225
AIC                         7362857.5616
BIC                          7364661.257

-- confusion_matrix --

           Predicted: -  Predicted: +
Actual: -       1033867        271715
Actual: +        319576        987674

-- confusion_metrics --

                       Value
Threshold             0.5000
Accuracy              0.7737
Precision             0.7842
Recall (Sensitivity)  0.7555
Specificity           0.7919
F1                    0.7696

==========
Unmatched | Unweighted - Link Model
==========
-- coef_table --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
const,14.4577,0.0227,637.8244,0.0,14.4132,14.5021,1900583.133,1.817994e+06,1.986924e+06
log_dist_km,-1.2838,0.0028,-458.3659,0.0,-1.2892,-1.2783,0.277,2.755000e-01,2.785000e-01

-- embedding_coefs --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
emb_hadamard_0,13.7449,0.2232,61.5729,0.0000,13.3074,14.1824,931842.4359,601628.8331,1.443299e+06
emb_hadamard_1,-2.5742,0.3709,-6.9410,0.0000,-3.3010,-1.8473,0.0762,0.0368,1.577000e-01
emb_hadamard_2,9.7584,0.3566,27.3628,0.0000,9.0594,10.4574,17298.4305,8598.9189,3.479922e+04
emb_hadamard_3,-0.1913,0.3197,-0.5984,0.5496,-0.8180,0.4353,0.8258,0.4413,1.545500e+00
emb_hadamard_4,5.5467,0.4286,12.9427,0.0000,4.7067,6.3867,256.3877,110.6896,5.938644e+02
...,...,...,...,...,...,...,...,...,...
emb_hadamard_123,-4.9029,0.2043,-23.9946,0.0000,-5.3034,-4.5024,0.0074,0.0050,1.110000e-02
emb_hadamard_124,-1.5737,0.2683,-5.8658,0.0000,-2.0996,-1.0479,0.2073,0.1225,3.507000e-01
emb_hadamard_125,9.1303,0.3871,23.5840,0.0000,8.3715,9.8891,9230.7192,4322.1772,1.971372e+04
emb_hadamard_126,-19.9939,0.3461,-57.7707,0.0000,-20.6723,-19.3156,0.0000,0.0000,0.000000e+00
emb_hadamard_127,-2.8880,0.1643,-17.5762,0.0000,-3.2101,-2.5660,0.0557,0.0404,7.680000e-02

-- diagnostics --

                                   Value
Dependent Variable                     y
No. Observations                 7838674
Df Model                           129.0
Df Residuals                   7838544.0
Converged                          False
Iterations                           200
Covariance Type                nonrobust
Log-Likelihood             -3069309.6705
LL-Null (intercept only)   -5433353.2559
LLR chi2                    4728087.1708
LLR p-value                          0.0
Pseudo R-squ. (McFadden's)        0.4351
AIC                         6138879.3411
BIC                         6140683.0365

-- confusion_matrix --

           Predicted: -  Predicted: +
Actual: -       1070202        235380
Actual: +        223639       1083611

-- confusion_metrics --

                       Value
Threshold             0.5000
Accuracy              0.8243
Precision             0.8215
Recall (Sensitivity)  0.8289
Specificity           0.8197
F1                    0.8252

----------
Distance-Matched | Weighted - Strength Model
----------
-- coef_table --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
const,1.0414,0.0211,49.3393,0.0,1.0001,1.0828,2.8333,2.7185,2.9530
log_dist_km,-0.1849,0.0051,-36.2867,0.0,-0.1948,-0.1749,0.8312,0.8230,0.8396

-- embedding_coefs --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
emb_hadamard_0,-0.7091,0.0748,-9.4853,0.0000,-0.8556,-0.5626,0.4921,0.4250,0.5697
emb_hadamard_1,1.0605,0.0619,17.1413,0.0000,0.9392,1.1817,2.8877,2.5579,3.2599
emb_hadamard_2,0.5712,0.0806,7.0862,0.0000,0.4132,0.7292,1.7704,1.5116,2.0733
emb_hadamard_3,0.5283,0.0498,10.5994,0.0000,0.4306,0.6260,1.6960,1.5382,1.8701
emb_hadamard_4,0.1522,0.0530,2.8738,0.0041,0.0484,0.2560,1.1644,1.0496,1.2917
...,...,...,...,...,...,...,...,...,...
emb_hadamard_123,-0.9997,0.0515,-19.4122,0.0000,-1.1006,-0.8987,0.3680,0.3327,0.4071
emb_hadamard_124,1.1642,0.0840,13.8665,0.0000,0.9996,1.3288,3.2033,2.7173,3.7763
emb_hadamard_125,-0.9473,0.0612,-15.4893,0.0000,-1.0672,-0.8275,0.3878,0.3440,0.4372
emb_hadamard_126,-0.8644,0.0520,-16.6230,0.0000,-0.9664,-0.7625,0.4213,0.3805,0.4665
emb_hadamard_127,1.3019,0.0818,15.9089,0.0000,1.1415,1.4622,3.6761,3.1314,4.3156

-- diagnostics --

                                   Value
Dependent Variable                     y
No. Observations                  854454
Df Model                           129.0
Df Residuals                    854324.0
Converged                           True
Iterations                            93
Covariance Type                nonrobust
Log-Likelihood              -512212.6219
LL-Null (intercept only)     -592262.381
LLR chi2                     160099.5182
LLR p-value                          0.0
Pseudo R-squ. (McFadden's)        0.1352
AIC                         1024685.2439
BIC                         1026200.8122

-- confusion_matrix --

           Predicted: -  Predicted: +
Actual: -         96066         45944
Actual: +         47956         94054

-- confusion_metrics --

                       Value
Threshold             0.5000
Accuracy              0.6694
Precision             0.6718
Recall (Sensitivity)  0.6623
Specificity           0.6765
F1                    0.6670

----------
Distance-Matched | Unweighted - Strength Model
----------
-- coef_table --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
const,-8.3023,0.0671,-123.6884,0.0,-8.4338,-8.1707,0.0002,0.0002,0.0003
log_dist_km,-0.2833,0.0047,-60.0434,0.0,-0.2925,-0.2740,0.7533,0.7464,0.7603

-- embedding_coefs --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
emb_hadamard_0,-1.0092,0.6802,-1.4837,0.1379,-2.3424,0.3240,0.3645,0.0961,1.382600e+00
emb_hadamard_1,-0.6386,0.6194,-1.0309,0.3026,-1.8527,0.5755,0.5280,0.1568,1.778000e+00
emb_hadamard_2,-22.2365,0.6267,-35.4791,0.0000,-23.4649,-21.0081,0.0000,0.0000,0.000000e+00
emb_hadamard_3,-2.4661,0.9151,-2.6949,0.0070,-4.2596,-0.6726,0.0849,0.0141,5.104000e-01
emb_hadamard_4,-3.6882,1.1988,-3.0766,0.0021,-6.0378,-1.3386,0.0250,0.0024,2.622000e-01
...,...,...,...,...,...,...,...,...,...
emb_hadamard_123,-5.2574,1.0403,-5.0539,0.0000,-7.2963,-3.2185,0.0052,0.0007,4.000000e-02
emb_hadamard_124,0.1027,1.2938,0.0793,0.9368,-2.4331,2.6384,1.1081,0.0878,1.399110e+01
emb_hadamard_125,13.3136,0.5996,22.2051,0.0000,12.1385,14.4887,605373.8970,186924.2513,1.960567e+06
emb_hadamard_126,-15.7637,0.6497,-24.2623,0.0000,-17.0371,-14.4903,0.0000,0.0000,0.000000e+00
emb_hadamard_127,-11.6112,0.5643,-20.5773,0.0000,-12.7172,-10.5052,0.0000,0.0000,0.000000e+00

-- diagnostics --

                                  Value
Dependent Variable                    y
No. Observations                 854454
Df Model                          129.0
Df Residuals                   854324.0
Converged                         False
Iterations                          200
Covariance Type               nonrobust
Log-Likelihood             -436861.8653
LL-Null (intercept only)    -592262.381
LLR chi2                    310801.0315
LLR p-value                         0.0
Pseudo R-squ. (McFadden's)       0.2624
AIC                         873983.7305
BIC                         875499.2988

-- confusion_matrix --

           Predicted: -  Predicted: +
Actual: -         99690         42320
Actual: +         30363        111647

-- confusion_metrics --

                       Value
Threshold             0.5000
Accuracy              0.7441
Precision             0.7251
Recall (Sensitivity)  0.7862
Specificity           0.7020
F1                    0.7544

----------
Unmatched | Weighted - Strength Model
----------
-- coef_table --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
const,1.3027,0.0221,59.0505,0.0,1.2595,1.346,3.6793,3.5236,3.8419
log_dist_km,-0.2890,0.0051,-56.8876,0.0,-0.2989,-0.279,0.7490,0.7416,0.7565

-- embedding_coefs --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
emb_hadamard_0,-0.4668,0.0781,-5.9768,0.0000,-0.6198,-0.3137,0.6270,0.5380,0.7307
emb_hadamard_1,0.6710,0.0856,7.8383,0.0000,0.5032,0.8388,1.9562,1.6540,2.3135
emb_hadamard_2,-1.0528,0.0295,-35.7397,0.0000,-1.1105,-0.9951,0.3490,0.3294,0.3697
emb_hadamard_3,1.3687,0.0696,19.6763,0.0000,1.2323,1.5050,3.9301,3.4292,4.5041
emb_hadamard_4,1.5277,0.0801,19.0781,0.0000,1.3708,1.6847,4.6076,3.9383,5.3906
...,...,...,...,...,...,...,...,...,...
emb_hadamard_123,-1.0499,0.0415,-25.2794,0.0000,-1.1313,-0.9685,0.3500,0.3226,0.3797
emb_hadamard_124,1.4030,0.0839,16.7227,0.0000,1.2386,1.5674,4.0674,3.4507,4.7944
emb_hadamard_125,-0.0015,0.0871,-0.0178,0.9858,-0.1723,0.1692,0.9985,0.8417,1.1844
emb_hadamard_126,2.0171,0.0808,24.9635,0.0000,1.8587,2.1755,7.5165,6.4156,8.8063
emb_hadamard_127,0.2624,0.0827,3.1742,0.0015,0.1004,0.4244,1.3000,1.1056,1.5286

-- diagnostics --

                                   Value
Dependent Variable                     y
No. Observations                  854454
Df Model                           129.0
Df Residuals                    854324.0
Converged                           True
Iterations                           162
Covariance Type                nonrobust
Log-Likelihood              -512799.5108
LL-Null (intercept only)     -592262.381
LLR chi2                     158925.7404
LLR p-value                          0.0
Pseudo R-squ. (McFadden's)        0.1342
AIC                         1025859.0216
BIC                           1027374.59

-- confusion_matrix --

           Predicted: -  Predicted: +
Actual: -         96914         45096
Actual: +         48949         93061

-- confusion_metrics --

                       Value
Threshold             0.5000
Accuracy              0.6689
Precision             0.6736
Recall (Sensitivity)  0.6553
Specificity           0.6824
F1                    0.6643

----------
Unmatched | Unweighted - Strength Model
----------
-- coef_table --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
const,-8.7848,0.0711,-123.5561,0.0,-8.9242,-8.6455,0.0002,0.0001,0.0002
log_dist_km,-0.2433,0.0047,-51.6376,0.0,-0.2525,-0.2340,0.7841,0.7769,0.7913

-- embedding_coefs --

,Coef.,Std.Err.,z,P>|z|,[0.025,0.975],Odds Ratio,OR 95% CI Low,OR 95% CI High
emb_hadamard_0,-21.2977,0.6727,-31.6582,0.0000,-22.6162,-19.9792,0.000000e+00,0.000000e+00,0.000000e+00
emb_hadamard_1,0.9148,0.9326,0.9809,0.3266,-0.9131,2.7427,2.496300e+00,4.013000e-01,1.552900e+01
emb_hadamard_2,4.9315,1.0877,4.5340,0.0000,2.7997,7.0632,1.385833e+02,1.643980e+01,1.168219e+03
emb_hadamard_3,17.2766,0.8810,19.6096,0.0000,15.5498,19.0034,3.185173e+07,5.664997e+06,1.790879e+08
emb_hadamard_4,-4.0982,1.2160,-3.3701,0.0008,-6.4816,-1.7148,1.660000e-02,1.500000e-03,1.800000e-01
...,...,...,...,...,...,...,...,...,...
emb_hadamard_123,15.7006,0.5987,26.2257,0.0000,14.5272,16.8740,6.586954e+06,2.037480e+06,2.129491e+07
emb_hadamard_124,3.5541,0.8037,4.4222,0.0000,1.9789,5.1293,3.495510e+01,7.234500e+00,1.688927e+02
emb_hadamard_125,-9.0324,1.1660,-7.7462,0.0000,-11.3178,-6.7470,1.000000e-04,0.000000e+00,1.200000e-03
emb_hadamard_126,6.7703,0.8934,7.5782,0.0000,5.0193,8.5213,8.715919e+02,1.513059e+02,5.020772e+03
emb_hadamard_127,-1.5788,0.4897,-3.2242,0.0013,-2.5386,-0.6191,2.062000e-01,7.900000e-02,5.385000e-01

-- diagnostics --

                                  Value
Dependent Variable                    y
No. Observations                 854454
Df Model                          129.0
Df Residuals                   854324.0
Converged                         False
Iterations                          200
Covariance Type               nonrobust
Log-Likelihood              -439447.772
LL-Null (intercept only)    -592262.381
LLR chi2                     305629.218
LLR p-value                         0.0
Pseudo R-squ. (McFadden's)        0.258
AIC                         879155.5441
BIC                         880671.1124

-- confusion_matrix --

           Predicted: -  Predicted: +
Actual: -        100533         41477
Actual: +         31423        110587

-- confusion_metrics --

                       Value
Threshold             0.5000
Accuracy              0.7433
Precision             0.7272
Recall (Sensitivity)  0.7787
Specificity           0.7079
F1                    0.7521

Embedding P-value Distribution

In [9]:
import os
os.makedirs('figures/agg/model_results', exist_ok=True)

for label in combo_paths:
    tbl = tables[(label, 'link')]['embedding_coefs']
    emb_nums = [int(i.replace('emb_hadamard_', '')) for i in tbl.index]
    emb_pvals = tbl['P>|z|']
    plt.figure(figsize=(14, 5))
    plt.scatter(emb_nums, emb_pvals)
    plt.xlim(left=min(emb_nums), right=max(emb_nums))
    plt.xlabel('Embedding dimension')
    plt.ylabel('P>|z|')
    plt.title(f'{label} - embedding p-values (link)')
    plt.tight_layout()
    plt.savefig(f'figures/agg/model_results/embs_pvals_link_{label.replace(" ", "_").replace("|", "")}.png')
    plt.show()

for label in combo_paths:
    tbl = tables[(label, 'strength')]['embedding_coefs']
    emb_nums = [int(i.replace('emb_hadamard_', '')) for i in tbl.index]
    emb_pvals = tbl['P>|z|']
    plt.figure(figsize=(14, 5))
    plt.scatter(emb_nums, emb_pvals)
    plt.xlim(left=min(emb_nums), right=max(emb_nums))
    plt.xlabel('Embedding dimension')
    plt.ylabel('P>|z|')
    plt.title(f'{label} - embedding p-values (strength)')
    plt.tight_layout()
    plt.savefig(f'figures/agg/model_results/embs_pvals_str_{label.replace(" ", "_").replace("|", "")}.png')
    plt.show()

C:\Users\User\AppData\Local\Temp\ipykernel_16208\2028408307.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\User\AppData\Local\Temp\ipykernel_16208\2028408307.py:30: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

### Distance Coefficient Decomposition

### Geographic Dependency Analysis (Tract + Category)

In [ ]:
# dependency (shrinkage-normalized) as a function of distance, per category pair
from scipy.stats import spearmanr

# --- per-edge shrunk DEP + distance (empirical-Bayes shrinkage; cross-category only) ---
#   DEP_shrunk = (cov + alpha*r0)/(v_i*v_j + alpha),  plotted as lift = DEP_shrunk / r0
#   (lift = 1 -> global-average dependency; >1 -> more dependent than typical)
e_combo, e_dist, e_cov, e_den = [], [], [], []
for u, v, data in G.edges(data=True):
    c1, c2 = u.split('||')[0], v.split('||')[0]
    if c1 == c2:                       # skip within-category (same POI type)
        continue
    dist = data.get('DIST_KM')
    cov = data.get('N_COVISITS')
    vi = G.nodes[u].get('total_visits')
    vj = G.nodes[v].get('total_visits')
    if dist is None or cov is None or vi is None or vj is None:
        continue
    e_combo.append(tuple(sorted((c1, c2))))
    e_dist.append(dist)
    e_cov.append(cov)
    e_den.append(vi * vj)

e_dist = np.asarray(e_dist, dtype='float64')
e_cov = np.asarray(e_cov, dtype='float64')
e_den = np.asarray(e_den, dtype='float64')
r0 = e_cov.sum() / e_den.sum()
alpha = np.median(e_den)
e_lift = ((e_cov + alpha * r0) / (e_den + alpha)) / r0   # lift over the global rate
print(f"per-edge shrinkage: r0 = {r0:.3e} | alpha = {alpha:.3e}")

# group (dist, lift) per unordered cross-category combo
combo_to_data = defaultdict(list)
for c, d, lf in zip(e_combo, e_dist, e_lift):
    combo_to_data[c].append((d, lf))

# --- rank by distance-sensitivity: |Spearman(dist, dep)| (rank-based, log/linear agree) ---
MIN_EDGES_RANK = 300   # need enough support for a stable correlation
rho = {}
for combo, vals in combo_to_data.items():
    if len(vals) < MIN_EDGES_RANK:
        continue
    dd = np.array([d for d, _ in vals])
    ll = np.array([x for _, x in vals])
    m = dd > 0
    if m.sum() < MIN_EDGES_RANK:
        continue
    r, _ = spearmanr(dd[m], ll[m])
    if np.isfinite(r):
        rho[combo] = r
top_combos = sorted(rho, key=lambda c: abs(rho[c]), reverse=True)[:12]
for i, c in enumerate(top_combos, 1):
    print(f'#{i}: {c} | rho = {rho[c]:+.3f} | n = {len(combo_to_data[c])}')

# --- shared axes: common distance bins/xlim + a common ylim across panels (lift units) ---
N_BINS = 15
MIN_PER_BIN = 15
pos = e_dist > 0
DIST_XLIM = tuple(np.percentile(e_dist[pos], [1, 99]))
bin_edges = np.geomspace(DIST_XLIM[0], DIST_XLIM[1], N_BINS + 1)

def binned(dists, lifts):
    dists, lifts = np.asarray(dists), np.asarray(lifts)
    m = dists > 0
    dists, lifts = dists[m], lifts[m]
    idx = np.digitize(dists, bin_edges[1:-1])
    centers, medians, lowers, uppers = [], [], [], []
    for b in range(N_BINS):
        mask = idx == b
        if mask.sum() < MIN_PER_BIN:
            continue
        centers.append(dists[mask].mean())
        medians.append(np.median(lifts[mask]))
        q25, q75 = np.percentile(lifts[mask], [25, 75])
        lowers.append(q25)
        uppers.append(q75)
    return (np.array(centers), np.array(medians), np.array(lowers), np.array(uppers))

# pre-pass: compute all panels + a shared y-range that brackets what's drawn
panel_stats, ylo, yhi = {}, np.inf, -np.inf
for combo in top_combos[:8]:
    st = binned([d for d, _ in combo_to_data[combo]], [x for _, x in combo_to_data[combo]])
    panel_stats[combo] = st
    if len(st[2]):
        ylo = min(ylo, st[2].min())
        yhi = max(yhi, st[3].max())
pad = 0.05 * (yhi - ylo) if np.isfinite(yhi - ylo) and yhi > ylo else 0
DIST_YLIM = (max(0.0, ylo - pad), yhi + pad)

# --- plot ---
n_cols = 4
n_rows = math.ceil(len(top_combos[:8]) / n_cols)
fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, n_rows * 4), sharex=True, sharey=True)
axes = axes.flatten()

for i, combo in enumerate(top_combos[:8]):
    ax = axes[i]
    centers, medians, lowers, uppers = panel_stats[combo]
    if not len(centers):
        continue
    ax.axhline(1.0, color='gray', linestyle='--', linewidth=1, zorder=0)  # global average
    ax.plot(centers, medians, color='steelblue', linewidth=1.5)
    ax.fill_between(centers, lowers, uppers, alpha=0.2, color='steelblue')
    ax.set_xscale('log')
    ax.set_xlim(DIST_XLIM)
    ax.set_ylim(DIST_YLIM)
    ax.text(0.95, 0.95, f"Rank: #{i+1}\nρ: {rho[combo]:+.2f}",
            transform=ax.transAxes, va='top', ha='right',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8, edgecolor='lightgray'))
    ax.set_title(f"{combo[0]} × {combo[1]}", fontsize=10)
    ax.set_xlabel('Distance (km)', fontsize=8)
    ax.set_ylabel('Dependency lift (× global rate)', fontsize=8)

for j in range(len(top_combos[:8]), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.savefig('imgs/agg/geo_cat_dep/dep_dist_distr.png', dpi=300)
plt.show()

In [ ]:
# --- global dep-vs-distance (shrinkage-normalized, all cross-category pairs pooled) ---
# per-edge shrunk DEP as lift over r0; axes forced to the per-combo limits for comparability.
dists, covs, dens = [], [], []
for u, v, data in G.edges(data=True):
    c1, c2 = u.split('||')[0], v.split('||')[0]
    if c1 == c2:
        continue
    dist = data.get('DIST_KM')
    cov = data.get('N_COVISITS')
    vi = G.nodes[u].get('total_visits')
    vj = G.nodes[v].get('total_visits')
    if dist is None or cov is None or vi is None or vj is None:
        continue
    dists.append(dist)
    covs.append(cov)
    dens.append(vi * vj)
dists = np.asarray(dists, dtype='float64')
covs = np.asarray(covs, dtype='float64')
dens = np.asarray(dens, dtype='float64')
r0 = covs.sum() / dens.sum()
alpha = np.median(dens)
lifts = ((covs + alpha * r0) / (dens + alpha)) / r0

N_BINS = 15
MIN_PER_BIN = 15
pos = dists > 0
dists, lifts = dists[pos], lifts[pos]

# reuse shared limits from the per-combo cell for comparability (fallback if run alone)
XLIM = DIST_XLIM if 'DIST_XLIM' in globals() else tuple(np.percentile(dists, [1, 99]))
bin_edges = np.geomspace(XLIM[0], XLIM[1], N_BINS + 1)
bin_idx = np.digitize(dists, bin_edges[1:-1])
centers, medians, lowers, uppers = [], [], [], []
for b in range(N_BINS):
    mask = bin_idx == b
    if mask.sum() < MIN_PER_BIN:
        continue
    centers.append(dists[mask].mean())
    medians.append(np.median(lifts[mask]))
    q25, q75 = np.percentile(lifts[mask], [25, 75])
    lowers.append(q25)
    uppers.append(q75)
centers = np.array(centers)
medians = np.array(medians)
lowers = np.array(lowers)
uppers = np.array(uppers)

fig, ax = plt.subplots(figsize=(4, 4))
ax.axhline(1.0, color='gray', linestyle='--', linewidth=1, zorder=0)  # global average
ax.plot(centers, medians, color='firebrick', linewidth=1.5)
ax.fill_between(centers, lowers, uppers, alpha=0.2, color='firebrick')
ax.set_xscale('log')
ax.set_xlim(XLIM)
if 'DIST_YLIM' in globals():
    ax.set_ylim(DIST_YLIM)

ax.text(0.95, 0.95, "Global",
        transform=ax.transAxes, va='top', ha='right',
        bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8, edgecolor='lightgray'))
ax.set_title("All cross-category pairs (global)", fontsize=10)
ax.set_xlabel('Distance (km)', fontsize=8)
ax.set_ylabel('Dependency lift (× global rate)', fontsize=8)
plt.tight_layout()
plt.savefig('imgs/agg/geo_cat_dep/global_dist_distr.png', dpi=300)
plt.show()

In [ ]:
# --- tract-level permutation dependency storage ---

# main loop
rows = []
for perm in tqdm(perms):
    s, t = perm
    for tract in tracts:
        nodes_in_tract = [n for n in G.nodes() if n.split('||')[1] == tract]
        target_node = next((n for n in nodes_in_tract if n.split('||')[0] == t), None)
        if target_node:
            # retrieve all incident edges whose neighbor is the chosen source cat
            edges_to_take = [
                (u, v) for (u, v) in G.edges(target_node) if v.split('||')[0] == s
            ]
            # store
            median_dep = np.median([G.edges[u, v].get('DEP', 0.0) for (u, v) in edges_to_take])
            sum_dep = np.sum([G.edges[u, v].get('DEP', 0.0) for (u, v) in edges_to_take])
            rows.append(
                {'tract': tract, 'source_cat': s, 'target_cat': t, 'median_dep': median_dep, 'sum_dep': sum_dep}
            )
        else:
            continue

# convert to df and save
dep_df = pd.DataFrame(rows)
dep_df.to_parquet('data/agg/undir_dep/cat_dep_undir.parquet', index=False)

print(f"Saved {len(dep_df)} rows â€” {dep_df['tract'].nunique()} tracts, {dep_df[['target_cat','source_cat']].drop_duplicates().shape[0]} perms")

In [ ]:
# --- mapping setup and plotting function ---

# import data
stats = pd.read_parquet('data/agg/undir_dep/cat_dep_undir.parquet')
cbg_gdf = gpd.read_file('data/geo/tl_2025_25_bg.shp').to_crs('EPSG:4326')

# agg shapefile up to tract level
cbg_gdf['tract'] = cbg_gdf['GEOID'].str.slice(0, 11)
tract_gdf = cbg_gdf.dissolve(by='tract', aggfunc='first')
tract_gdf = tract_gdf.reset_index()

def map_dep(to_plot, map_vers='perm', perm_type=None, save_name='unnamed', rank=None):
    
    if map_vers == 'single':
        mapping_df = stats[stats['source_cat'].eq(to_plot) | stats['target_cat'].eq(to_plot)]
        mapping_df = mapping_df.groupby('tract')['median_dep'].median().reset_index()
        title_text = f"Median Visit Dependency of Permutations Involving {to_plot} by Census Tract"
    
    elif map_vers == 'perm':
        first, second = to_plot
        if perm_type == 'grouped':
            mapping_df = stats[stats['source_cat'].isin(first) & (stats['target_cat'].isin(second))]
            mapping_df = mapping_df.groupby('tract')['median_dep'].median().reset_index()
            title_text = f"Median Visit Dependency: {first} â†’ {second} by Census Tract"
        else:
            filtered_df = stats[(stats['source_cat'] == first) & (stats['target_cat'] == second)]
            mapping_df = filtered_df[['tract', 'median_dep']]
            title_text = f"Visit Dependency: {first} â†’ {second} by Census Tract"

    merged_gdf = tract_gdf.merge(mapping_df, on='tract')

    fig, ax = plt.subplots(figsize=(10, 8))

    merged_gdf.plot(
        column='median_dep', 
        cmap='Reds', 
        linewidth=0.4, 
        ax=ax, 
        edgecolor=".4",
        legend=True
    )

    if rank is not None:
        ax.text(
            0.98, 0.97, f"Rank #{rank}",
            transform=ax.transAxes,
            ha='right', va='top',
            fontsize=13, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='gray', alpha=0.8)
        )
    
    plt.xticks(rotation=90)
    ax.set_title(title_text, fontsize=14, fontweight='bold', pad=15)
    ax.set_axis_off()
    plt.tight_layout()
    plt.savefig(
        f'imgs/agg/geo_cat_dep/maps/gcv_{save_name}.png', 
        dpi=500,
        bbox_inches='tight',
    )
    plt.close(fig)

    print(f'{to_plot} plotted and saved successfully.')

In [ ]:
# --- map the same ones found from KS test ---

# load stuff back in if needed

if 'stats' not in globals() and 'stats' not in locals() or stats is None or \
   'G' not in globals() and 'G' not in locals() or G is None:
    
    print('df or network not loaded or is None. Loading in.')
    stats = pd.read_parquet('data/agg/undir_dep/cat_dep_undir.parquet')
    
    with open(fpath, 'rb') as f:
        G = pickle.load(f)

# feed the function

if not top_combos:
    with open('data/agg/geo_cat_dep/top_combos.pkl', 'rb') as f:
        top_combos = pickle.load(f)

topN = top_combos[:8]

for i, combo in enumerate(topN, 1):
    elem1, elem2 = combo[0].split(' ')[0].lower(), combo[1].split(' ')[0].lower()
    map_dep(combo, save_name=f"{elem1}_{elem2}", rank=i)